### ISSUE TITLE
Client prefs do not work

### ISSUE THREAD

**Issue by Tiagoquix** [Mikusch/deathrun#28] opened 2024-02-09 05:18 UTC
When I use !settings and tell the plugin to not show chat tips anymore it still shows them.

**Comment by Mikusch** [comment] 2024-12-08 18:00
Seems that no one else reported this issue and I can't reproduce it, so I'll be closing this for now. If it occurs again, create a new issue.

**Closed by Mikusch** 2024-12-08 18:00 UTC
